### ISSUE TITLE
关于您最新的论文中2b模型的效果

### ISSUE THREAD

**Issue by Kausal-Lei** [aitsc/GLMKD#1]
您好，我看到您做了直接Finetune T1(110M),T2(340M),T3(10B)模型的效果，也看到了通过您方法蒸馏的S2模型能达到很好的效果，我想知道您是否做过直接Finetune S2(2B)模型的效果？通过您方法蒸馏的S2模型 比直接SFT效果能好多少呢？

**Comment by aitsc** [comment]
See section 6.3.

**Comment by Kausal-Lei** [comment]
谢谢~
